// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: common/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentType defines the role of the agent
type AgentType int32

const (
	AgentType_AGENT_TYPE_UNSPECIFIED AgentType = 0
	AgentType_CLIENT                 AgentType = 1
	AgentType_GATEWAY                AgentType = 2
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNSPECIFIED",
		1: "CLIENT",
		2: "GATEWAY",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNSPECIFIED": 0,
		"CLIENT":                 1,
		"GATEWAY":                2,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_agent_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_common_proto_agent_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{0}
}

// RouteAction defines what to do with matching packets
type RouteAction int32

const (
	RouteAction_ROUTE_ACTION_UNSPECIFIED RouteAction = 0
	RouteAction_FORWARD                  RouteAction = 1 // Forward through gateway
	RouteAction_DIRECT                   RouteAction = 2 // Send directly (local routing)
	RouteAction_DENY                     RouteAction = 3 // Drop the packet
)

// Enum value maps for RouteAction.
var (
	RouteAction_name = map[int32]string{
		0: "ROUTE_ACTION_UNSPECIFIED",
		1: "FORWARD",
		2: "DIRECT",
		3: "DENY",
	}
	RouteAction_value = map[string]int32{
		"ROUTE_ACTION_UNSPECIFIED": 0,
		"FORWARD":                  1,
		"DIRECT":                   2,
		"DENY":                     3,
	}
)

func (x RouteAction) Enum() *RouteAction {
	p := new(RouteAction)
	*p = x
	return p
}

func (x RouteAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteAction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_agent_proto_enumTypes[1].Descriptor()
}

func (RouteAction) Type() protoreflect.EnumType {
	return &file_common_proto_agent_proto_enumTypes[1]
}

func (x RouteAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteAction.Descriptor instead.
func (RouteAction) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{1}
}

// AgentStatus represents the operational state
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_ONLINE                   AgentStatus = 1
	AgentStatus_OFFLINE                  AgentStatus = 2
	AgentStatus_ERROR                    AgentStatus = 3
	AgentStatus_MAINTENANCE              AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "ONLINE",
		2: "OFFLINE",
		3: "ERROR",
		4: "MAINTENANCE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"ONLINE":                   1,
		"OFFLINE":                  2,
		"ERROR":                    3,
		"MAINTENANCE":              4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_agent_proto_enumTypes[2].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_common_proto_agent_proto_enumTypes[2]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest is sent by agents during initial connection
type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AgentId                string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                              // UUID of the agent
	UserKey                string                 `protobuf:"bytes,2,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`                                              // User API key for authentication
	Type                   AgentType              `protobuf:"varint,3,opt,name=type,proto3,enum=proto.AgentType" json:"type,omitempty"`                                             // Client or Gateway
	ProtocolVersion        string                 `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                      // Protocol version (e.g., "1.0.0")
	CertificateFingerprint string                 `protobuf:"bytes,5,opt,name=certificate_fingerprint,json=certificateFingerprint,proto3" json:"certificate_fingerprint,omitempty"` // SHA256 fingerprint of client cert
	Metadata               *AgentMetadata         `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                           // Additional agent information
	Bandwidth              int32                  `protobuf:"varint,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`                                                        // Bandwidth in KB/s, 0 for unlimited
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_common_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *RegisterRequest) GetType() AgentType {
	if x != nil {
		return x.Type
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *RegisterRequest) GetCertificateFingerprint() string {
	if x != nil {
		return x.CertificateFingerprint
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

// AgentMetadata contains platform and version information
type AgentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                                                                   // Operating system (linux, darwin, windows)
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`                                                                               // Architecture (amd64, arm64)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Agent version
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // Hostname of the machine
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom labels for filtering/grouping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_common_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentMetadata) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// RegisterResponse is returned after successful registration
type RegisterResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Accepted                bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                                               // Whether registration was accepted
	SessionId               string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                             // Unique session identifier
	AssignedIp              string                 `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                                          // Assigned overlay IP address
	ServerVersion           string                 `protobuf:"bytes,4,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`                                 // Server protocol version
	MinimumSupportedVersion string                 `protobuf:"bytes,5,opt,name=minimum_supported_version,json=minimumSupportedVersion,proto3" json:"minimum_supported_version,omitempty"` // Minimum compatible version
	ErrorMessage            string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                    // Error description if not accepted
	ServerConfig            *ServerConfig          `protobuf:"bytes,7,opt,name=server_config,json=serverConfig,proto3" json:"server_config,omitempty"`                                    // Server configuration parameters
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_common_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *RegisterResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *RegisterResponse) GetMinimumSupportedVersion() string {
	if x != nil {
		return x.MinimumSupportedVersion
	}
	return ""
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetServerConfig() *ServerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

// ServerConfig contains server-side configuration
type ServerConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GatewayIp         string                 `protobuf:"bytes,1,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`                          // Server's overlay IP (usually .0.1)
	Mtu               int32                  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`                                                      // Maximum transmission unit
	KeepaliveInterval int32                  `protobuf:"varint,3,opt,name=keepalive_interval,json=keepaliveInterval,proto3" json:"keepalive_interval,omitempty"` // Heartbeat interval in seconds
	KeepaliveTimeout  int32                  `protobuf:"varint,4,opt,name=keepalive_timeout,json=keepaliveTimeout,proto3" json:"keepalive_timeout,omitempty"`    // Connection timeout in seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_common_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerConfig) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *ServerConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ServerConfig) GetKeepaliveInterval() int32 {
	if x != nil {
		return x.KeepaliveInterval
	}
	return 0
}

func (x *ServerConfig) GetKeepaliveTimeout() int32 {
	if x != nil {
		return x.KeepaliveTimeout
	}
	return 0
}

// HeartbeatRequest is sent periodically to maintain connection
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session identifier
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Current timestamp
	Stats         *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`                          // Agent statistics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_common_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// AgentStats contains performance and traffic metrics
type AgentStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BytesSent       uint64                 `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`                   // Total bytes sent
	BytesReceived   uint64                 `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`       // Total bytes received
	PacketsSent     uint64                 `protobuf:"varint,3,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`             // Total packets sent
	PacketsReceived uint64                 `protobuf:"varint,4,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"` // Total packets received
	Errors          uint32                 `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`                                          // Error count
	Drops           uint32                 `protobuf:"varint,6,opt,name=drops,proto3" json:"drops,omitempty"`                                            // Dropped packet count
	CpuUsage        float32                `protobuf:"fixed32,7,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU usage percentage
	MemoryUsage     uint64                 `protobuf:"varint,8,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`             // Memory usage in bytes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_common_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *AgentStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *AgentStats) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *AgentStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *AgentStats) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *AgentStats) GetDrops() uint32 {
	if x != nil {
		return x.Drops
	}
	return 0
}

func (x *AgentStats) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentStats) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// HeartbeatResponse acknowledges heartbeat
type HeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Alive               bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`                                                          // Server is alive
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                   // Server timestamp
	ShouldRefreshRoutes bool                   `protobuf:"varint,3,opt,name=should_refresh_routes,json=shouldRefreshRoutes,proto3" json:"should_refresh_routes,omitempty"` // Client should re-fetch routes
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                                       // Optional message from server
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_common_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatResponse) GetShouldRefreshRoutes() bool {
	if x != nil {
		return x.ShouldRefreshRoutes
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DataPacket represents an IP packet being relayed
type DataPacket struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                              // Session identifier
	SourceAgentId      string                 `protobuf:"bytes,2,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`                // Source agent UUID
	DestinationAgentId string                 `protobuf:"bytes,3,opt,name=destination_agent_id,json=destinationAgentId,proto3" json:"destination_agent_id,omitempty"` // Destination agent UUID (empty for gateway)
	Payload            []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                   // IP packet data
	Sequence           uint32                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                // Sequence number for ordering
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                               // Packet timestamp
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	mi := &file_common_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DataPacket) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DataPacket) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *DataPacket) GetDestinationAgentId() string {
	if x != nil {
		return x.DestinationAgentId
	}
	return ""
}

func (x *DataPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataPacket) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DataPacket) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// RouteRequest asks for routing configuration
type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session identifier
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // Agent UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_common_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RouteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouteRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// RouteResponse provides routing rules
type RouteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rules            []*RoutingRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`                                                 // List of routing rules
	DefaultGatewayId string                 `protobuf:"bytes,2,opt,name=default_gateway_id,json=defaultGatewayId,proto3" json:"default_gateway_id,omitempty"` // Default gateway agent ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_common_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RouteResponse) GetRules() []*RoutingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *RouteResponse) GetDefaultGatewayId() string {
	if x != nil {
		return x.DefaultGatewayId
	}
	return ""
}

// RoutingRule defines a routing policy
type RoutingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`          // Rule identifier
	Action        RouteAction            `protobuf:"varint,2,opt,name=action,proto3,enum=proto.RouteAction" json:"action,omitempty"` // Action to take
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`               // Destination CIDR
	GatewayId     string                 `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`  // Gateway agent ID (for forward action)
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                    // Rule priority (lower = higher priority)
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                      // Whether rule is active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_common_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RoutingRule) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RoutingRule) GetAction() RouteAction {
	if x != nil {
		return x.Action
	}
	return RouteAction_ROUTE_ACTION_UNSPECIFIED
}

func (x *RoutingRule) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RoutingRule) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RoutingRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RoutingRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// StatusUpdate allows agents to report status changes
type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`  // Session identifier
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`        // Agent UUID
	Status        AgentStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=proto.AgentStatus" json:"status,omitempty"` // New status
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                       // Optional status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_common_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StatusUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StatusUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatusResponse acknowledges status update
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"` // Update was received
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`            // Optional response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_common_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_agent_proto protoreflect.FileDescriptor

const file_common_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x18common/proto/agent.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\buser_key\x18\x02 \x01(\tR\auserKey\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.proto.AgentTypeR\x04type\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x17certificate_fingerprint\x18\x05 \x01(\tR\x16certificateFingerprint\x120\n" +
	"\bmetadata\x18\x06 \x01(\v2\x14.proto.AgentMetadataR\bmetadata\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\x05R\tbandwidth\"\xde\x01\n" +
	"\rAgentMetadata\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x128\n" +
	"\x06labels\x18\x05 \x03(\v2 .proto.AgentMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12%\n" +
	"\x0eserver_version\x18\x04 \x01(\tR\rserverVersion\x12:\n" +
	"\x19minimum_supported_version\x18\x05 \x01(\tR\x17minimumSupportedVersion\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x128\n" +
	"\rserver_config\x18\a \x01(\v2\x13.proto.ServerConfigR\fserverConfig\"\x9b\x01\n" +
	"\fServerConfig\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x01 \x01(\tR\tgatewayIp\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\x05R\x03mtu\x12-\n" +
	"\x12keepalive_interval\x18\x03 \x01(\x05R\x11keepaliveInterval\x12+\n" +
	"\x11keepalive_timeout\x18\x04 \x01(\x05R\x10keepaliveTimeout\"\x94\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x05stats\x18\x03 \x01(\v2\x11.proto.AgentStatsR\x05stats\"\x8e\x02\n" +
	"\n" +
	"AgentStats\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x04R\rbytesReceived\x12!\n" +
	"\fpackets_sent\x18\x03 \x01(\x04R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x04 \x01(\x04R\x0fpacketsReceived\x12\x16\n" +
	"\x06errors\x18\x05 \x01(\rR\x06errors\x12\x14\n" +
	"\x05drops\x18\x06 \x01(\rR\x05drops\x12\x1b\n" +
	"\tcpu_usage\x18\a \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\b \x01(\x04R\vmemoryUsage\"\xb1\x01\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x15should_refresh_routes\x18\x03 \x01(\bR\x13shouldRefreshRoutes\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xf5\x01\n" +
	"\n" +
	"DataPacket\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0fsource_agent_id\x18\x02 \x01(\tR\rsourceAgentId\x120\n" +
	"\x14destination_agent_id\x18\x03 \x01(\tR\x12destinationAgentId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\rR\bsequence\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"H\n" +
	"\fRouteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"g\n" +
	"\rRouteResponse\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.proto.RoutingRuleR\x05rules\x12,\n" +
	"\x12default_gateway_id\x18\x02 \x01(\tR\x10defaultGatewayId\"\xc9\x01\n" +
	"\vRoutingRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.proto.RouteActionR\x06action\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tR\tgatewayId\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"\x8e\x01\n" +
	"\fStatusUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.proto.AgentStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"N\n" +
	"\x0eStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*@\n" +
	"\tAgentType\x12\x1a\n" +
	"\x16AGENT_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01\x12\v\n" +
	"\aGATEWAY\x10\x02*N\n" +
	"\vRouteAction\x12\x1c\n" +
	"\x18ROUTE_ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aFORWARD\x10\x01\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x02\x12\b\n" +
	"\x04DENY\x10\x03*`\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\v\n" +
	"\aOFFLINE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0f\n" +
	"\vMAINTENANCE\x10\x042\xba\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\x12B\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponse(\x010\x01\x125\n" +
	"\tRelayData\x12\x11.proto.DataPacket\x1a\x11.proto.DataPacket(\x010\x01\x126\n" +
	"\tGetRoutes\x12\x13.proto.RouteRequest\x1a\x14.proto.RouteResponse\x12:\n" +
	"\fUpdateStatus\x12\x13.proto.StatusUpdate\x1a\x15.proto.StatusResponseB,Z*github.com/taills/EasyAnyLink/common/protob\x06proto3"

var (
	file_common_proto_agent_proto_rawDescOnce sync.Once
	file_common_proto_agent_proto_rawDescData []byte
)

func file_common_proto_agent_proto_rawDescGZIP() []byte {
	file_common_proto_agent_proto_rawDescOnce.Do(func() {
		file_common_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_agent_proto_rawDesc), len(file_common_proto_agent_proto_rawDesc)))
	})
	return file_common_proto_agent_proto_rawDescData
}

var file_common_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_common_proto_agent_proto_goTypes = []any{
	(AgentType)(0),                // 0: proto.AgentType
	(RouteAction)(0),              // 1: proto.RouteAction
	(AgentStatus)(0),              // 2: proto.AgentStatus
	(*RegisterRequest)(nil),       // 3: proto.RegisterRequest
	(*AgentMetadata)(nil),         // 4: proto.AgentMetadata
	(*RegisterResponse)(nil),      // 5: proto.RegisterResponse
	(*ServerConfig)(nil),          // 6: proto.ServerConfig
	(*HeartbeatRequest)(nil),      // 7: proto.HeartbeatRequest
	(*AgentStats)(nil),            // 8: proto.AgentStats
	(*HeartbeatResponse)(nil),     // 9: proto.HeartbeatResponse
	(*DataPacket)(nil),            // 10: proto.DataPacket
	(*RouteRequest)(nil),          // 11: proto.RouteRequest
	(*RouteResponse)(nil),         // 12: proto.RouteResponse
	(*RoutingRule)(nil),           // 13: proto.RoutingRule
	(*StatusUpdate)(nil),          // 14: proto.StatusUpdate
	(*StatusResponse)(nil),        // 15: proto.StatusResponse
	nil,                           // 16: proto.AgentMetadata.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_common_proto_agent_proto_depIdxs = []int32{
	0,  // 0: proto.RegisterRequest.type:type_name -> proto.AgentType
	4,  // 1: proto.RegisterRequest.metadata:type_name -> proto.AgentMetadata
	16, // 2: proto.AgentMetadata.labels:type_name -> proto.AgentMetadata.LabelsEntry
	6,  // 3: proto.RegisterResponse.server_config:type_name -> proto.ServerConfig
	17, // 4: proto.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: proto.HeartbeatRequest.stats:type_name -> proto.AgentStats
	17, // 6: proto.HeartbeatResponse.timestamp:type_name -> google.protobuf.Timestamp
	17, // 7: proto.DataPacket.timestamp:type_name -> google.protobuf.Timestamp
	13, // 8: proto.RouteResponse.rules:type_name -> proto.RoutingRule
	1,  // 9: proto.RoutingRule.action:type_name -> proto.RouteAction
	2,  // 10: proto.StatusUpdate.status:type_name -> proto.AgentStatus
	3,  // 11: proto.AgentService.Register:input_type -> proto.RegisterRequest
	7,  // 12: proto.AgentService.Heartbeat:input_type -> proto.HeartbeatRequest
	10, // 13: proto.AgentService.RelayData:input_type -> proto.DataPacket
	11, // 14: proto.AgentService.GetRoutes:input_type -> proto.RouteRequest
	14, // 15: proto.AgentService.UpdateStatus:input_type -> proto.StatusUpdate
	5,  // 16: proto.AgentService.Register:output_type -> proto.RegisterResponse
	9,  // 17: proto.AgentService.Heartbeat:output_type -> proto.HeartbeatResponse
	10, // 18: proto.AgentService.RelayData:output_type -> proto.DataPacket
	12, // 19: proto.AgentService.GetRoutes:output_type -> proto.RouteResponse
	15, // 20: proto.AgentService.UpdateStatus:output_type -> proto.StatusResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_common_proto_agent_proto_init() }
func file_common_proto_agent_proto_init() {
	if File_common_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_agent_proto_rawDesc), len(file_common_proto_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_agent_proto_goTypes,
		DependencyIndexes: file_common_proto_agent_proto_depIdxs,
		EnumInfos:         file_common_proto_agent_proto_enumTypes,
		MessageInfos:      file_common_proto_agent_proto_msgTypes,
	}.Build()
	File_common_proto_agent_proto = out.File
	file_common_proto_agent_proto_goTypes = nil
	file_common_proto_agent_proto_depIdxs = nil
}
